[source."git+https://github.com/dzbarsky/rules_rust?rev=b56cbaa8465e74127f1ea216f813cd377295ad81"]
git = "https://github.com/dzbarsky/rules_rust"
rev = "b56cbaa8465e74127f1ea216f813cd377295ad81"
replace-with = "vendored-sources"

[source."git+https://github.com/helix-editor/nucleo.git?rev=4253de9faabb4e5c6d81d946a5e35a90f87347ee"]
git = "https://github.com/helix-editor/nucleo.git"
rev = "4253de9faabb4e5c6d81d946a5e35a90f87347ee"
replace-with = "vendored-sources"

[source."git+https://github.com/nornagon/crossterm?branch=nornagon%2Fcolor-query"]
git = "https://github.com/nornagon/crossterm"
branch = "nornagon/color-query"
replace-with = "vendored-sources"

[source."git+https://github.com/nornagon/ratatui?branch=nornagon-v0.29.0-patch"]
git = "https://github.com/nornagon/ratatui"
branch = "nornagon-v0.29.0-patch"
replace-with = "vendored-sources"

[source."git+https://github.com/openai-oss-forks/tokio-tungstenite?rev=132f5b39c862e3a970f731d709608b3e6276d5f6"]
git = "https://github.com/openai-oss-forks/tokio-tungstenite"
rev = "132f5b39c862e3a970f731d709608b3e6276d5f6"
replace-with = "vendored-sources"

[source."git+https://github.com/openai-oss-forks/tungstenite-rs?rev=9200079d3b54a1ff51072e24d81fd354f085156f"]
git = "https://github.com/openai-oss-forks/tungstenite-rs"
rev = "9200079d3b54a1ff51072e24d81fd354f085156f"
replace-with = "vendored-sources"
